url=https://my.businessnext.com/app/businessnext/Home/Summary
excelpath=src/test/resources/Testdata/testdata.xlsx
browser=edge
chromemode=--incognito
edgemode=
firefoxmode=-private

#Login Details
username=sumit.patil@businessnext.com
password=Cogent@1111 

#Login Page Locators Details
usernameid=TxtName
passwordid=TxtPassword
loginbutton=dual-login-sso-btn

#Summary Page Locators
cases=//i[@class='icon-obj9']